# Blueprint para WAHA API en Render (Plan Gratuito)
# Este servicio utilizará tu base de datos 'n8n-db' existente.

services:
  - type: web
    name: waha-api-service # ¡Nuevo nombre para tu servicio de WAHA API!
    plan: free # Plan Gratuito (se "dormirá" si no hay tráfico)
    runtime: image
    image:
      url: devlikeapro/waha:latest # ¡Esta es la imagen de Docker de WAHA!
    region: oregon # Asegúrate de que esta región coincida con tu base de datos de n8n

    envVars:
      - key: DATABASE_URL # Conexión a tu base de datos 'n8n-db' existente
        fromDatabase:
          name: n8n-db
          property: connectionString
      - key: JWT_SECRET # Clave secreta para WAHA (se genera automáticamente)
        generateValue: true
      - key: SECRET_KEY # Otra clave secreta para WAHA (se genera automáticamente)
        generateValue: true
      - key: WEBHOOK_URL # URL a la que WAHA enviará los mensajes recibidos
        value: https://n8n-service-pbqp.onrender.com/webhook/waha-webhook # <--- ¡IMPORTANTE! n8n escuchará aquí (URL de n8n)
      - key: WEBHOOK_SECRET # Clave para asegurar los webhooks (se genera automáticamente)
        generateValue: true
      - key: PORT # El puerto que WAHA usará dentro del contenedor
        value: 10000 # Un puerto común para servicios web en Render

# NOTA: No definimos una sección 'databases' en este archivo
# porque estamos usando tu 'n8n-db' existente, que ya está gestionada
# por el Blueprint de tu servicio n8n principal.
      
